// TEST/FIXTURE DATA -- not real mechanic knowledge. Clearly marked isFixture:
// true throughout so production retrieval (which excludes fixtures) and
// fixture-separation tests can both rely on this flag.
export const FIXTURE_ENTRIES = [
  {
    id: "fx-1",
    sourceType: "mechanic_authored",
    system: "starting",
    subsystem: "ignition",
    component: null,
    symptom: "engine cranks but does not start",
    possibleCause: "no spark due to failed ignition coil",
    diagnosticTest: "check for spark at the plug with a spark tester",
    expectedResult: "visible spark; none indicates a coil or ignition module fault",
    repairAction: "replace the ignition coil",
    vehicleApplicability: [],
    confidence: "high",
    riskLevel: "routine_safe",
    reviewStatus: "published",
    isFixture: true,
  },
  {
    id: "fx-2",
    sourceType: "trusted_technical_source",
    system: "fuel",
    subsystem: "delivery",
    component: "fuel pump",
    symptom: "engine cranks but does not start",
    possibleCause: "fuel pump not delivering pressure",
    diagnosticTest: "check fuel pressure at the rail with a gauge",
    expectedResult: "pressure within spec; below spec indicates pump or filter fault",
    repairAction: "replace fuel pump or filter as indicated",
    vehicleApplicability: [{ make: "Toyota" }],
    confidence: "medium",
    riskLevel: "requires_caution",
    reviewStatus: "published",
    isFixture: true,
  },
  {
    id: "fx-3",
    sourceType: "ai_inferred",
    system: "brakes",
    subsystem: "hydraulic",
    component: null,
    symptom: "soft brake pedal",
    possibleCause: "air in brake lines",
    diagnosticTest: "inspect for spongy pedal feel after bleeding",
    expectedResult: "firm pedal after proper bleed",
    repairAction: "bleed brake lines",
    vehicleApplicability: [],
    confidence: "low",
    riskLevel: "safety_critical",
    reviewStatus: "published",
    isFixture: true,
  },
  {
    id: "fx-4-draft",
    sourceType: "mechanic_authored",
    system: "cooling",
    subsystem: null,
    component: null,
    symptom: "engine overheats at idle",
    possibleCause: "failed cooling fan relay",
    diagnosticTest: "listen for fan activation at high coolant temp",
    expectedResult: "fan runs; silence indicates relay or fan fault",
    repairAction: "replace fan relay",
    vehicleApplicability: [],
    confidence: "medium",
    riskLevel: "routine_safe",
    reviewStatus: "draft", // not published -- must never be retrieved
    isFixture: true,
  },
];
